### ISSUE TITLE
Validation: Confirmed rule always validate to false

### ISSUE THREAD

**Issue by FR6** [aerni/statamic-livewire-forms#27]
When using the [`confirmed` rule](https://laravel.com/docs/9.x/validation#rule-confirmed), the validation always return `false`.

A work around is to use the [`same` rule](https://laravel.com/docs/9.x/validation#rule-same) and by adding `data.` to the field name:
`same:data.<field name>`

Using:
- Statamic Livewire Forms v6.2.0
- Statamic v3.3.54

**Comment by aerni** [comment]
Can you please provide a simple form blueprint that reproduces this issue?

**Comment by FR6** [comment]
Here is a blueprint for the confirmed rule:

```
sections:
  main:
    display: Main
    fields:
      -
        handle: pharmacien_declarant_email
        field:
          input_type: text
          antlers: false
          display: Courriel
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
          validate:
            - required
            - email
          width: 50
          group: pharmacien_declarant_coordonnees
      -
        handle: pharmacien_declarant_email_confirmation
        field:
          input_type: text
          antlers: false
          display: 'Confirmer votre courriel'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
          validate:
            - required
            - 'confirmed'
          width: 50
          group: pharmacien_declarant_coordonnees
```
